# Generated by Django 4.0.3 on 2022-04-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_picture_user_pseudo_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/faces'),
        ),
    ]
