# Generated by Django 4.0.3 on 2022-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notes_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/faces'),
        ),
    ]
