# Generated by Django 4.0.3 on 2022-04-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Pseudo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Role',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='images/faces')),
                ('Pseudo', models.CharField(blank=True, max_length=150, null=True)),
                ('Role', models.CharField(blank=True, max_length=150, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
