# Generated by Django 4.0.3 on 2022-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='actif',
            field=models.BooleanField(default=False, verbose_name='actif'),
        ),
    ]
