# Generated by Django 4.0.3 on 2022-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseorder',
            options={'verbose_name': 'warehouseorder', 'verbose_name_plural': 'warehouseorders'},
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison'), ('AR', 'Archive')], max_length=2, null=True, verbose_name='type de commande'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison'), ('AR', 'Archive')], max_length=2, null=True, verbose_name='type de commande'),
        ),
    ]
