# Generated by Django 4.0.3 on 2022-04-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_warehouseorder_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Name',
            new_name='name',
        ),
    ]
