# Generated by Django 4.0.3 on 2022-04-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_actif'),
        ('order', '0004_clientorder_is_defect_supplyorder_is_defect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison')], max_length=2, null=True, verbose_name='type de commande'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='inventory.warehouse', verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('BC', 'Bon de commande'), ('FF', 'Facture finale'), ('BL', 'Bon de livraison')], max_length=2, null=True, verbose_name='type de commande'),
        ),
    ]
