# Generated by Django 4.0.3 on 2022-04-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_clientorder_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='is_defect',
        ),
        migrations.RemoveField(
            model_name='supplyorder',
            name='is_defect',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='is_defect',
        ),
    ]
