# Generated by Django 4.0.3 on 2022-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_clientorder_is_defect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='nis_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Numéro d’Identification Statistique'),
        ),
    ]
