# Generated by Django 4.0.3 on 2022-04-21 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_alter_warehouseorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyorder',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='supplyorder',
            name='supply_type',
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Creer par'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifier par'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='warehouse_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders_to_deliver', to=settings.AUTH_USER_MODEL, verbose_name='livreur'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders', to='inventory.warehouse', verbose_name='Depot de récéption'),
        ),
    ]
