# Generated by Django 4.0.3 on 2022-04-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_supplyorder_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseorder',
            options={'ordering': ('-created',), 'verbose_name': 'warehouseorder', 'verbose_name_plural': 'warehouseorders'},
        ),
    ]
